# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
name: Test and Push

on:
  push:
    branches:
      - master
    # paths:
    #   - '**/*' # Trigger the workflow if any file changes in any directory

jobs:
  test-main-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies for local branch
        run: npm install

      - name: Run tests on local branch
        run: npm test

  test-local-branch:
    runs-on: ubuntu-latest
    
      - name: Switch to main branch
        run: git checkout vrushabhhuchchannavar-patch-1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies for main branch
        run: npm install

      - name: Run tests on master branch
        run: npm test





# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "master" ]
#   # pull_request:
#   #   branches: [ "master" ]

# jobs:
#   my-job:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: 14

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test
