name: Run Tests on Multiple Branches

on:
  push:
    branches:
      # - master
      - vrushabhhuchchannavar-patch-1

jobs:
  testing-the-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies for local branch
        run: npm install

      - name: Run tests on local
        run: npm test || true

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.json

      - name: checkout to master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies for main branch
        run: npm install

      - name: Run tests on master branch
        run: npm test || true









# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "master" ]
#   # pull_request:
#   #   branches: [ "master" ]

# jobs:
#   my-job:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: 14

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test
