name: Run Tests on Multiple Branches

on:
  push:
    branches:
      # - master
      - vrushabhhuchchannavar-patch-1

jobs:
  testing-the-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node
        with:
          node-version: 14

      - name: Install dependencies for local branch
        run: npm install

      - name: Run tests on local
        run: npm test || true

      - name: Upload test results
        uses: actions/upload-artifact
        with:
          name: test-results-local
          path: test-results.json

      - name: checkout to master branch
        uses: actions/checkout
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node
        with:
          node-version: 14

      - name: Install dependencies for main branch
        run: npm install

      - name: Run tests on master branch
        run: npm test || true

      - name: Upload test results
        uses: actions/upload-artifact
        with:
          name: test-results-master
          path: test-results.json

      - name: Compare test results
          run: |
            # Extract relevant metrics from the working branch
            main_failed=$(echo "${{ steps.testing-the-branches.outputs.numFailedTests }}")
            main_passed=$(echo "${{ steps.testing-the-branches.outputs.numPassedTests }}")
            main_pending=$(echo "${{ steps.testing-the-branches.outputs.numPendingTests }}")

            # Extract relevant metrics from the master branch
            master_failed=$(echo "${{ steps.testing-the-branches.outputs.numFailedTests-master }}")
            master_passed=$(echo "${{ steps.testing-the-branches.outputs.numPassedTests-master }}")
            master_pending=$(echo "${{ steps.testing-the-branches.outputs.numPendingTests-master }}")










# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "master" ]
#   # pull_request:
#   #   branches: [ "master" ]

# jobs:
#   my-job:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: 14

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test
